apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: frontend1
spec:
  provider:
    onepasswordSDK:
      vault: Frontend1
      auth:
        serviceAccountSecretRef:
          name: onepassword-connect-token
          namespace: external-secrets
          key: token